name: HlsService
description: |
  Video streaming service
version: 1.0
category: Web
maintainer: Aquiline Drones <devteam@aquilinedrones.com>
license: UNLICENSED
projectURL: https://code.aquilinedrones.com/aquiline/farmcat
