version: '2'
services:
  mongo-cluster:
    restart: always
    environment:
      MONGO_SERVICE_NAME: mongo-cluster
      CATTLE_SCRIPT_DEBUG: ${debug}
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${default_admin_pwd}
    entrypoint: /opt/rancher/bin/entrypoint.sh
    command:
    - --auth
    image: mongo:3.4
    labels:
      io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.scheduler.affinity:host_label: ${host_label}
      io.rancher.container.hostname_override: container_name
      io.rancher.sidekicks: mongo-base, mongo-datavolume
      io.database.role: spartacus-db
    ports:
      - 27017:27017/tcp
