version: '2'
catalog:
  name: "TPPD"
  version: "1.0"
  description: "TPP cloud API daemon"
  questions:
    - variable: tpp_app_url
      description: "URL where this server will be accessed from"
      label: "Server URL"
      type: "string"
      required: true
      default: https://tpp.aquiline.io
    - variable: tpp_oidc_url
      description: "OIDC URL to contact SSO server"
      label: "OIDC Endpoint"
      type: "string"
      required: true
      default: http://sso:8080/auth/realms/aquiline.io
    - variable: tpp_admin_user
      description: "Service account username"
      label: "Admin User"
      type: "string"
      required: true
      default: tpman@aquiline.io
    - variable: tpp_admin_secret
      description: "Password for service account"
      label: "Admin Password"
      type: "password"
      required: true
      default: ChangeMeChangeMe
    - variable: tpp_client_id
      description: "TPMAN client ID or name"
      label: "Client ID"
      type: "string"
      required: true
      default: tpman
    - variable: tpp_client_secret
      description: "Client secret UUID obtained from SSO"
      label: "Client Secret"
      type: "password"
      required: true
      default: ChangeMeChangeMe
    - variable: tpp_cluster_secret
      description: "Cluster secret is used for HA setup"
      label: "Cluster Secret"
      type: "password"
      required: true
      default: "vvoO4751dEiayZchFwmtMt_dbMmeR3bYUZitlM0Ahzhqt-x4RiJM6F9dS8spvV9WLDKvUGD-pM3CiSauVbptsw=="
    - variable: "tpp_cors"
      description: "CORS allowed to consume this application. Setting * will disable CORS credential."
      label: "CORS Allowed FQDN"
      type: "string"
      required: false
    - variable: "tppd_image"
      label: "TPPD Image"
      description: "Image to use"
      required: true
      default: "aquilinedrones/tppd:1.0"
      type: enum
      options:
        - aquilinedrones/tppd:1.0
    - variable: "tppd_image_custom"
      label: "Custom TPPD Image"
      description: "Use a custom TPPD image. This will override value of TPPD Image."
      required: false
      type: string
    - variable: "sso_service"
      description: "SSO service to use. You can reference the service as 'sso' by setting this."
      label: "SSO Service"
      default: ""
      required: false
      type: "service"
    - variable: debug_mode
      description: "Runs TPPD in debug mode. This increases log verbosity."
      label: "Enable Debug Mode"
      type: boolean
      required: true
      default: false
    # --- common param: host affinity
    - variable: host_affinity_label
      description: "The stack will launch on one of the hosts that has this label."
      label: "Host Affinity Label"
      type: string
      required: false
    # --- common param: storage; subst vols_required = `volumes ("Volume Name"_data)`
    - variable: datavolume_name
      label: "Volume Base Name"
      description: |
        To store the application data in volume(s), enter the base volume name that should be used. One or more volumes will be created with this value as the prefix. 
        By default, all volumes created will be host scoped named. See "Storage Driver" for other storage options.
      required: false
      type: string
    - variable: volume_exists
      label: "Volume Exists"
      description: |
        Check this if you have already created the volumes ("Volume Name"_data). Remember to set the "Volume Storage Driver" too. Do not fill 
        in "NFS Driver Host" or "NFS Driver Volume Path".
      required: true
      type: boolean
      default: false
    #- variable: storage_size
    #  label: "Volume Storage Size"
    #  description: "Limit the size of the log volume (in megabytes). Defaults to unlimited."
    #  required: false
    #  type: int
    - variable: storage_driver
      label: "Volume Storage Driver"
      description: |
        To use a stack scoped volume backed by a persistent storage service, enter the name
        of an existing storage driver (e.g. "rancher-nfs"). This also requires "Volume Name" to be set.
      required: true
      type: enum
      default: "local"
      options:
        - local
        - rancher-nfs
    - variable: storage_driver_nfsopts_host
      label: "NFS Driver Host"
      description: |
        Specify a NFS hostname instead of the default NFS server. Only fill in this option if "Volume Storage Driver" is 
        set to "rancher-nfs", and the volume does not already exist.
      required: false
      type: string
    - variable: storage_driver_nfsopts_export
      label: "NFS Driver Volume Path"
      description: |
        Specify the exported base path on the NFS server (e.g. "/storage/nfsvol"). The full directory(ies) created 
        on the NFS server will be this path and the volume name(s). Do not append the "/" at the end. This exported base path 
        must already exist on the NFS server. Only fill in this option if "Volume Storage Driver" is set to "rancher-nfs", and 
        the volume does not already exist.
      required: false
      type: string
    - variable: storage_retain_volume
      label: "Retain NFS Volume"
      description: Keep the volumes created even after this stack gets deleted. This option has no effect if the volume(s) already exists.
      required: true
      type: boolean
      value: false
    # --- common param: repull
    - variable: repull_image
      description: "Pull from registry source even if the host already have a local image with the same tag."
      label: "Reload Images"
      type: enum
      options:
        - always
        - never
      required: true
      default: "never"
    # --- common param: custom registry
    - variable: docker_registry_name
      description: "Pull from private registry. Leave blank to pull from public Docker Hub."
      label: "Private Registry"
      type: string
      required: false
    # --- common param: limit memory, remove docker_memory_swap_limit
    - variable: docker_memory_limit
      label: "Limit Memory"
      description: "Maxiumum memory that each container can use (in megabytes). Defaults to unlimited. Do not specify a value lower than 4."
      type: int
      required: false
    - variable: docker_memory_kernel_limit
      label: "Limit Kernel Memory"
      description: |
        Maxiumum kernel memory that each container can use (in megabytes). Defaults to unlimited. If this value is lower than Limit Memory, 
        the container will experience OOM error if it runs out of kernel memory, unless memory is unlimited, in which case it will wait 
        for memory released.
      type: int
      required: false
    # --- common param: limit cpu
    - variable: docker_cpu_quota_limit
      label: "Limit CPUs"
      description: |
        Limit CPU resources (in multiples of 100,000 microseconds). Defaults to unlimited. For example, "150000" limits the container 
        to 1.5 CPUs.
      type: int
      required: false
    - variable: docker_cpu_weight_limit
      label: "CPU Weight"
      description: |
        A number lower than the default will have less priority when competing for CPU resources and vice verse.
      type: int
      required: true
      default: 1024

services:
  tppd:
    scale: 1
    retain_ip: true
    health_check:
      response_timeout: 2000
      healthy_threshold: 5
      port: 4000
      unhealthy_threshold: 30
      initializing_timeout: 600000
      interval: 30000
      strategy: recreate
      request_line: GET "/health/ping" "HTTP/1.0"
      reinitializing_timeout: 120000
